# Generated by Django 5.1 on 2024-08-29 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PracApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
