# Generated by Django 5.1 on 2024-08-12 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PracApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='admin_customize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
