# Generated by Django 5.1 on 2024-08-12 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PracApp', '0002_admin_customize'),
    ]

    operations = [
        migrations.DeleteModel(
            name='admin_customize',
        ),
    ]
