# Generated by Django 5.1 on 2024-08-12 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PracApp', '0003_delete_admin_customize'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={},
        ),
    ]
