# Generated by Django 5.1 on 2024-08-12 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PracApp', '0005_alter_student_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
    ]
