# Generated by Django 5.1 on 2024-08-12 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PracApp', '0007_alter_student_first_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Registered Student'},
        ),
    ]
