# Generated by Django 5.1 on 2024-08-12 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PracApp', '0008_alter_student_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='student',
            name='roll_number',
            field=models.IntegerField(verbose_name='Roll Number'),
        ),
    ]
