# Generated by Django 5.1 on 2024-08-26 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=30, unique=True)),
                ('user_email', models.EmailField(default='user@gmail.com', max_length=254, unique=True)),
                ('user_age', models.IntegerField()),
                ('user_country', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
