# Generated by Django 5.1 on 2024-08-31 13:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user',
            new_name='Webuser',
        ),
        migrations.AlterModelOptions(
            name='webuser',
            options={'ordering': ['user_age'], 'verbose_name': 'User Model'},
        ),
    ]
